- app/models/customer.rb
- app/models/list_order.rb
- app/models/list_purchase.rb
- app/models/order.rb
- app/models/product.rb
- app/models/supplier.rb
Se modifico y añadió validaciones a respectivos modelos,  list_orders, list_purchases, etc
> se agrego validaciones a los modelos

- app/controllers/products_controller.rb
el crud basico de products controller
> se hizo crud de products controller

- Gemfile
- Gemfile.lock
- app/controllers/products_controller.rb
- app/views/products/index.html.erb
- app/views/shared/_navbar.html.erb
- db/seeds.rb
- seeds
- display de products
-  table con bootstrap
> index de products en table

- app/controllers/products_controller.rb
- app/views/products/new.html.erb
- app/views/products/show.html.erb
- app/views/shared/_products_form_new.html.erb
> se realizo la creación del form y parte basica de la vista show

- Gemfile
- Gemfile.lock
- app/controllers/list_purchases_controller.rb
- app/controllers/products_controller.rb
- app/controllers/purchases_controller.rb
- app/models/purchase.rb
- app/views/list_purchases/new.html.erb
- app/views/purchases/new.html.erb
- app/views/shared/_purchase_form.html.erb
- config/routes.rb
- db/seeds.rb
- test/controllers/list_purchases_controller_test.rb
Se avanza logica para agregar productos al inventario
> Add purchases to inventory

- Gemfile
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_sidebar.scss
- app/views/list_purchases/new.html.erb
- app/views/pages/dashboard.html.erb
- app/views/products/edit.html.erb
- app/views/products/index.html.erb
- app/views/products/new.html.erb
- app/views/products/show.html.erb
- app/views/purchases/new.html.erb
- app/views/shared/_sidebar.html.erb
Se agrega sidebar para hacer tests
> Add sidebar for tests

- Gemfile.lock
- app/views/products/edit.html.erb
- app/views/products/show.html.erb
contenido en Table y resize de los botones editar y borrar
> Product Show

- app/controllers/list_orders_controller.rb
- app/views/list_orders/new.html.erb
- app/views/orders/new.html.erb
- app/views/shared/_sidebar.html.erb
Se corrige bug en funcion de generar una nueva venta
Se agrega link hacia generar nueva venta en el sidebar
> se corrige error en funcion de generar nuevas ordenes

- app/controllers/orders_controller.rb
- app/controllers/purchases_controller.rb
- app/models/order.rb
- app/models/purchase.rb
- app/models/user.rb
- db/migrate/20220202175622_add_user_ref_to_orders.rb
- db/migrate/20220202175632_add_user_ref_to_purchases.rb
- db/schema.rb
> Se agregan referencias a usuario a las tablas de Order y Purchase

- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar_home.html.erb
structure html and some css of homepage
> homepage structure

- Gemfile
- Gemfile.lock
- app/models/product.rb
> se implemento generador de codigo de 8 digitos

- app/controllers/list_purchases_controller.rb
- app/controllers/purchases_controller.rb
- app/views/list_purchases/index.html.erb
Se corrige formulario de supplier
> Deploy heroku errors

- app/views/pages/dashboard.html.erb
> se cambio la vista dshboard

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
Cambio del navbar para el usuario
> Navbar 2.0

- app/assets/stylesheets/components/_dashboard.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_table_dashboard.scss
- app/controllers/pages_controller.rb
- app/views/pages/dashboard.html.erb
- app/views/products/index.html.erb
Se avanza estilos para el dashboard
> Products list dashboard

- app/controllers/pages_controller.rb
- app/views/pages/movements.html.erb
movements orders & purchases mixed
> movements orders & purchases mixed

- app/controllers/pages_controller.rb
- app/views/pages/dashboard.html.erb
se complementa el pie chart de dashboard
> se arreglo pie chart

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_card.scss
- app/views/pages/dashboard.html.erb
- app/views/pages/movements.html.erb
- db/seeds.rb
-front de movements
-seeds de compras y ventas
> movements & seeds

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/dashboard.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar_home.html.erb
Reverts danielh27/yupay-project#71
> Revert "navbar y home"

- app/assets/stylesheets/pages/_home.scss
- app/views/shared/_navbar_home.html.erb
- app/views/shared/_navbar_user_home.html.erb
> home y navbar

- app/assets/stylesheets/components/_new_order.scss
- app/controllers/customers_controller.rb
- app/controllers/list_orders_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/suppliers_controller.rb
- app/javascript/plugins/init_sweetalert.js
- app/policies/customer_policy.rb
- app/policies/list_order_policy.rb
- app/views/orders/new.html.erb
- app/views/purchases/new.html.erb
- db/migrate/20220209195425_change_tax_code_from_integer_to_string.rb
- db/schema.rb
- test/controllers/customers_controller_test.rb
- test/policies/customer_policy_test.rb
Se agrega boton para agregar nuevos clientes
Se agrega seleccion de cliente para generar una nueva venta
Se crea controlador de customer y policy para pundit
Se agregan estilos
> Styles purchases orders

- app/views/pages/dashboard.html.erb
- app/views/shared/_products_form_new.html.erb
- db/seeds.rb
Creacion de Productos / Dashboard / seeds
> Creacion de Productos / Dashboard / seeds

- app/controllers/list_purchases_controller.rb
- app/controllers/purchases_controller.rb
- app/javascript/plugins/init_sweetalert.js
- app/policies/list_purchase_policy.rb
- app/views/list_orders/index.html.erb
- app/views/list_purchases/_confirm_modal_item.html.erb
- app/views/list_purchases/_purchase_item.html.erb
- app/views/list_purchases/_quantity_form.html.erb
- app/views/list_purchases/_results.html.erb
- app/views/list_purchases/create.json.jbuilder
- app/views/list_purchases/index.html.erb
Estilos para seccion de compras
> Purchases feature styles

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_products_index.scss
- app/views/pages/movements.html.erb
> Responsive movements
